import Image from "next/image";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Wordmark from "@/components/Wordmark";
import { CEO, COMPANY, DEMOCRATIZATION, HERITAGE, HISTORY, HISTORY_INTRO, METHODS, NOW, SITE, TRUST } from "@/lib/site";

const external = { target: "_blank", rel: "noopener noreferrer" };

export default function Home() {
  return <>
    <Header />
    <main id="main">
      <section id="top" className="relative min-h-[100svh] overflow-hidden bg-purple-deep text-white">
        <Image src="/images/hero-living.jpg" alt="현대적인 거실에 놓인 케어렉스 리클라이너 안마의자" fill priority sizes="100vw" className="object-cover object-center" />
        <div className="hero-veil absolute inset-0" /><div className="grain absolute inset-0 opacity-35" />
        <div className="relative z-10 mx-auto flex min-h-[100svh] max-w-6xl flex-col justify-end px-5 pb-16 pt-28 md:justify-center md:px-8 md:pb-24">
          <p className="section-label fade-up !text-cyan-soft">{SITE.positioning}</p>
          <Wordmark size="hero" showKo className="fade-up-delay mt-5" />
          <p className="fade-up-delay-2 mt-8 max-w-xl text-xl leading-relaxed text-white/90 md:text-2xl">{SITE.thesis}</p>
          <p className="fade-up-delay-2 mt-5 max-w-lg text-sm leading-relaxed text-white/75 md:text-base">회복을 더 가까이. 케어렉스는 고품질 헬스케어가 일상의 누구에게나 닿도록, 오래 쌓아온 케어의 기준을 다시 제안합니다.</p>
          <div className="fade-up-delay-2 mt-9 flex flex-wrap gap-3"><a href={SITE.smartStoreUrl} {...external} className="rounded-sm bg-cyan px-6 py-3 text-sm font-bold text-purple-deep transition hover:bg-cyan-soft">스마트스토어</a><a href="#lead" className="rounded-sm border border-white/35 px-6 py-3 text-sm font-medium transition hover:border-cyan-soft hover:text-cyan-soft">케어렉스의 리드</a></div>
        </div>
      </section>

      <section id="lead" className="bg-paper px-5 py-20 md:px-8 md:py-32">
        <div className="mx-auto max-w-6xl"><p className="section-label">{COMPANY.label}</p><div className="brand-rule mt-4" /><div className="mt-7 grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:gap-20"><div><p className="chapter-index">01 — LEAD</p><h1 className="font-display mt-4 max-w-3xl whitespace-pre-line text-3xl leading-snug text-ink md:text-5xl">{COMPANY.headline}</h1></div><p className="max-w-xl self-end text-base leading-relaxed text-muted md:text-lg">{COMPANY.intro}</p></div>
          <div className="mt-16 space-y-12 md:mt-24 md:space-y-18">{COMPANY.chapters.map((chapter, index) => <article key={chapter.title} className="reveal grid gap-4 border-t border-stone-deep pt-7 md:grid-cols-[8rem_1fr] md:gap-10"><p className="chapter-index">0{index + 1}</p><div><h2 className="font-display max-w-3xl text-2xl leading-snug text-ink md:text-3xl">{chapter.title}</h2><p className="mt-4 max-w-3xl text-sm leading-relaxed text-muted md:text-base">{chapter.body}</p></div></article>)}</div>
          <blockquote className="reveal mt-20 border-l-2 border-cyan bg-stone/45 px-6 py-7 md:px-9"><p className="max-w-4xl text-lg leading-relaxed text-ink-soft md:text-2xl">“{DEMOCRATIZATION.quote}”</p><footer className="mt-5 text-sm text-muted">— {CEO.name} {CEO.title} · {DEMOCRATIZATION.source} ({DEMOCRATIZATION.sourceDate})</footer></blockquote>
        </div>
      </section>

      <section id="method" className="bg-purple px-5 py-20 text-white md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><p className="section-label !text-cyan-soft">Methods</p><div className="brand-rule mt-4" /><div className="mt-7 grid gap-8 md:grid-cols-2 md:gap-16"><h2 className="font-display text-3xl leading-snug md:text-5xl">기술은 조용하게,<br />회복은 분명하게.</h2><p className="self-end max-w-xl text-sm leading-relaxed text-white/75 md:text-base">특별한 하루를 위한 과장보다, 자주 돌아올 수 있는 감도를 만듭니다. 케어렉스의 세 가지 방식은 몸을 다루는 태도이자 일상에 회복을 들이는 방법입니다.</p></div><div className="mt-16 grid gap-8 md:grid-cols-3 md:gap-10">{METHODS.map((method) => <article key={method.code} className="reveal border-t border-cyan/45 pt-6"><p className="chapter-index !text-cyan-soft">{method.code}</p><h3 className="font-display mt-4 text-2xl md:text-3xl">{method.title}</h3><p className="mt-4 text-sm leading-relaxed text-white/75">{method.body}</p></article>)}</div></div></section>

      <section id="now" className="bg-stone px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1fr_.9fr] md:items-end md:gap-20"><div><p className="section-label">{NOW.label}</p><div className="brand-rule mt-4" /><p className="chapter-index mt-7">03 — NOW</p><h2 className="font-display mt-4 whitespace-pre-line text-3xl leading-snug text-ink md:text-5xl">{NOW.title}</h2><p className="mt-6 max-w-xl text-base leading-relaxed text-muted">{NOW.body}</p></div><div className="reveal border-l border-purple/25 pl-7 md:pl-10"><div className="flex flex-wrap gap-2">{NOW.pills.map((pill) => <span key={pill} className="rounded-full border border-purple/25 px-3 py-1.5 text-xs font-semibold tracking-wide text-purple">{pill}</span>)}</div><a href={SITE.smartStoreUrl} {...external} className="mt-10 inline-flex rounded-sm bg-purple px-6 py-3.5 text-sm font-bold text-white transition hover:bg-purple-deep">공식 스마트스토어 열기</a><p className="mt-4 text-sm leading-relaxed text-muted">제품 확인, 주문, 결제는 공식 스마트스토어에서 진행됩니다.</p></div></div></section>

      <section id="history" className="bg-paper px-5 py-20 md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><p className="section-label">History Archive</p><div className="brand-rule mt-4" /><p className="chapter-index mt-7">04 — HISTORY</p><h2 className="font-display mt-4 text-3xl leading-snug text-ink md:text-5xl">제품은 지나가도,<br />케어의 질문은 남습니다.</h2><p className="mt-6 text-base leading-relaxed text-muted md:text-lg">{HISTORY_INTRO} 각 모델은 그 시절의 생활과 공간을 위해 고민했던 케어렉스의 기록입니다.</p></div><div className="mt-14 grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{HISTORY.map((item) => <article key={item.id} className="reveal group"><div className="relative aspect-[4/3] overflow-hidden bg-stone"><Image src={item.image} alt={`${item.nameKo} ${item.code} 아카이브 이미지`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-[1.025]" /></div><p className="mt-5 text-[0.68rem] font-bold tracking-[0.16em] text-purple-soft">{item.era}</p><h3 className="font-display mt-2 text-2xl text-ink">{item.nameKo} <span className="text-base text-muted">{item.code}</span></h3><p className="mt-1 text-sm text-muted">{item.nameEn}</p><p className="mt-3 text-sm leading-relaxed text-muted">{item.summary}</p><p className="mt-4 text-xs font-semibold tracking-wide text-purple">판매 종료 · 아카이브</p></article>)}</div></div></section>

      <section id="heritage" className="bg-stone px-5 py-20 md:px-8 md:py-32"><div className="mx-auto max-w-6xl"><p className="section-label">Heritage</p><div className="brand-rule mt-4" /><div className="mt-7 grid gap-8 md:grid-cols-2 md:gap-16"><div><p className="chapter-index">05 — HERITAGE</p><h2 className="font-display mt-4 text-3xl leading-snug text-ink md:text-5xl">오래 쌓은 경험으로,<br />다음의 회복을 만듭니다.</h2></div><p className="self-end max-w-xl text-base leading-relaxed text-muted">국내 안마의자 1세대로 시작해 글로벌 공급 경험과 독자 브랜드의 시간을 지나왔습니다. 우리의 연혁은 더 많은 사람에게 회복이 닿기 위한 준비의 기록입니다.</p></div><ol className="mt-16 grid gap-7 md:grid-cols-5">{HERITAGE.map((item) => <li key={item.year} className="reveal border-t border-purple/30 pt-5"><p className="text-xs font-bold tracking-[0.16em] text-cyan">{item.year}</p><h3 className="font-display mt-3 text-xl text-ink">{item.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted">{item.body}</p></li>)}</ol><blockquote className="reveal mt-20 border-l-2 border-purple bg-paper/70 px-6 py-7 md:px-9"><p className="max-w-4xl text-base leading-relaxed text-ink-soft md:text-xl">“{CEO.quote}”</p><footer className="mt-5 text-sm text-muted">— {CEO.name} {CEO.title} · {CEO.source} ({CEO.sourceDate})</footer></blockquote></div></section>

      <section id="trust" className="bg-paper px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-6xl"><p className="section-label">Trust</p><div className="brand-rule mt-4" /><div className="mt-7 grid gap-8 md:grid-cols-2 md:gap-16"><h2 className="font-display text-3xl text-ink md:text-5xl">믿을 수 있는<br />경로만 남깁니다.</h2><p className="self-end max-w-xl text-base leading-relaxed text-muted">구매, 상담, A/S 그리고 기록까지. 케어렉스와 연결되는 모든 채널을 명확하게 열어 둡니다.</p></div><div className="mt-16 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{TRUST.map((item) => <article key={item.title} className="reveal border-t border-stone-deep pt-6"><h3 className="text-sm font-bold tracking-[0.14em] text-purple">{item.title}</h3><p className="mt-4 text-sm leading-relaxed text-ink-soft">{item.body}</p>{item.title === "브랜드 소식" && <a href={SITE.blogUrl} {...external} className="mt-5 inline-block text-sm font-semibold text-purple hover:underline">공식 블로그 방문하기 →</a>}</article>)}</div></div></section>

      <section className="relative overflow-hidden bg-purple-deep px-5 py-20 text-white md:px-8 md:py-28"><div className="grain absolute inset-0 opacity-30" /><div className="relative mx-auto max-w-3xl text-center"><Wordmark size="lg" showKo /><p className="section-label mt-8 !text-cyan-soft">A quiet close</p><h2 className="font-display mt-5 text-3xl leading-snug md:text-5xl">회복을 시작하는 길은,<br />더 단순해도 됩니다.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-relaxed text-white/75 md:text-base">케어렉스의 현재 제품과 구매 안내는 공식 스마트스토어에서 확인하세요. 우리는 그 경험의 앞과 뒤를 오래 지원하겠습니다.</p><a href={SITE.smartStoreUrl} {...external} className="mt-10 inline-flex rounded-sm bg-cyan px-7 py-3.5 text-sm font-bold text-purple-deep transition hover:bg-cyan-soft">스마트스토어로 가기</a></div></section>
    </main>
    <Footer />
  </>;
}